### ISSUE TITLE
Lunch and learn checklist

### ISSUE THREAD

**Issue by mediajunkie** [cagov/main#7]
- [x] Update ordinal number: This one is the fifth
- [x] Line up speaker(s): Anne
- [x] Agree on topic: "Working in and with government (AKA Public Administration 101)"
- [x] Check in with speaker Aug 9
- [x] Get working title
- [x] Get blurb
- [x] Update calendar
- [x] Check in with speaker(s) 1 week out
- [x] Promote the week of
- [x] Start meeting early with background music
- [x] Record presentation
- [x] Stop recording before Q&A
- [x] Gather slide(s) from presenter(s)
- [x] Upload slide(s) to Team Drive
- [x] Upload video to Team Drive
- [ ] Announce archived content in slack
- [ ] Add to some master index once it exists

**Comment by abquirarte** [comment]
@mediajunkie want to keep this as an open issue?

**Comment by mediajunkie** [comment]
I don't need to keep my checklist on this board or in github if it clutters things up, but I'll close this issue once I confirm that I've completed the archiving tasks for the 5th L&L
